name: terminal
description: This is a simple yet customizable terminal emulator written in Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  xterm: ^3.5.0
  dartssh2: ^2.5.0
  flutter_pty: ^0.4.0
  after_layout: ^1.1.0
  file_picker: ^5.0.1
  path: ^1.8.2
  bitsdojo_window: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cascadia Mono
      fonts:
        - asset: fonts/CascadiaMonoPL.ttf
